server.port=8080
spring.application.name=product

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExists=true
spring.datasource.username=root
spring.datasource.password=integrator
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379


# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# Logging
logging.level.root=INFO
logging.level.com.app.product=DEBUG

#actuators
management.endpoints.web.exposure.include= *
